name: jwst_validation_notebooks

channels:
- astropy
- astropy-ci-extras
- http://ssb.stsci.edu/astroconda
- defaults

dependencies:
- python=3.6
- numpy=1.15.2
- matplotlib
- astropy
- scipy
- jupyter
- pip
- ci-watson

- pip:
  - git+https://github.com/spacetelescope/stsci.imagestats.git@1.6.2
  - git+https://github.com/mfixstsci/nbpages.git
  - git+https://github.com/spacetelescope/jwst.git