name: jwst_validation_notebooks

channels:
- astropy
- astropy-ci-extras
- http://ssb.stsci.edu/astroconda
- defaults

dependencies:
- python=3.6
- numpy=1.15.2
- matplotlib
- astropy
- scipy
- jupyter

- pip:
  - stsci.imagestats>=1.4
  - git+https://github.com/eteq/nbpages.git
  - git+https://github.com/spacetelescope/jwst.git